- hosts: all
  sudo: yes
  remote_user: vagrant
  
  tasks:
    - name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
      command: host -t A ansible.cc
      register: ns
      ignore_errors: yes

    - name: Pushes new resolver configuration is resolver fails
      lineinfile: regexp="^nameserver " line="nameserver 8.8.8.8" dest=/etc/resolv.conf
      when: ns|failed

    - name: Checks if resolver is working properly with new nameserver
      command: host -t A ansible.cc

    #- name: Final greeting
    #  pause: prompt="Pritisnite enter"

    - debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

