- hosts: all
  sudo: yes
  remote_user: vagrant
  
  tasks:

    - hostname: name=foreman.localdomain

    #- name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
    #  command: host -t A ansible.cc
    #  register: ns
    #  ignore_errors: yes

    #- name: Pushes new resolver configuration is resolver fails
    #  lineinfile: regexp="^nameserver " line="nameserver 8.8.8.8" dest=/etc/resolv.conf
    #  when: ns|failed

    #- name: Checks if resolver is working properly with new nameserver
    #  command: host -t A ansible.cc

    #- name: Final greeting
    #  pause: prompt="Pritisnite enter"

    #- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

    - name: install epel release
      yum: name=epel-release

    - name: foreman repos install
      yum: name=http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm state=present
 
    - name: foreman 1.7 repos release install
      yum: name=http://yum.theforeman.org/releases/1.7/el7/x86_64/foreman-release.rpm state=present

    - name: foreman installer
      yum: name=foreman-installer

    - name: run foreman installer
      command: foreman-installer --foreman-admin-username=admin --foreman-admin-password=changeme --puppet-srv-domain=localdomain --foreman-proxy-dns-zone=localdomain --foreman-servername=foreman.localdomain --foreman-proxy-registered-name=foreman.localdomain
